import pytest
import json
import io
from src.agents.report import compile_report, generate_report_pdf, generate_report_json
from src.graph.state import AudioInput, TranscriptionResult, TranscriptionSegment, PIIScanResult, CallReport, QAScoringResult


def test_pii_scan_import_consistency():
    """Test that demonstrates the root cause of the PIIScanResult error.

    ERROR: pydantic_core._pydantic_core.ValidationError:
    pii_scan: Input should be a dictionary or an instance of PIIScanResult
    [type=dataclass_type, input_value=PIIScanResult(...), input_type=PIIScanResult]

    ROOT CAUSE: Inconsistent imports!

    In src/agents/intake.py line 12:
        from graph.state import PIIScanResult  ← WRONG: relative import (no src. prefix)

    This causes PIIScanResult to be imported twice:
    1. As: src.graph.state.PIIScanResult (via report.py imports)
    2. As: graph.state.PIIScanResult (via intake.py relative import)

    Pydantic treats these as different classes and rejects the dataclass validation!

    THE FIX: Use consistent absolute imports everywhere.
    Change line 12 in src/agents/intake.py from:
        from graph.state import PIIScanResult, PipeLineState
    To:
        from src.graph.state import PIIScanResult, PipeLineState
    """
    # This test verifies that PIIScanResult is correctly imported
    # If the imports are inconsistent, Pydantic will reject it

    # Import using the correct path
    from src.graph.state import PIIScanResult as CorrectPIIScanResult

    pii_result = CorrectPIIScanResult(pii_detected=True, affected_fields=["email"])

    state = {
        "audio_input": AudioInput(audio_bytes=b"123", filename="demo.wav", call_id="call-123"),
        "transcription": TranscriptionResult(
            segments=[TranscriptionSegment(start=0.0, end=1.0, text="hello", confidence=0.95)],
            call_id="call-123",
        ),
        "pii_scan": pii_result,
    }

    # This test will pass when imports are consistent
    updated = compile_report(state)
    assert updated["call_report"].pii_scan is not None
    assert updated["call_report"].pii_scan.pii_detected is True


def test_compile_report_with_pii_scan():
    """Test that compile_report works correctly with PIIScanResult.

    This test passes when the import inconsistency is fixed.
    """
    pii_result = PIIScanResult(pii_detected=False, affected_fields=[])

    state = {
        "audio_input": AudioInput(audio_bytes=b"123", filename="demo.wav", call_id="call-123"),
        "transcription": TranscriptionResult(
            segments=[TranscriptionSegment(start=0.0, end=1.0, text="hello", confidence=0.95)],
            call_id="call-123",
        ),
        "pii_scan": pii_result,
    }

    updated = compile_report(state)
    assert updated["call_report"].call_id == "call-123"
    assert updated["call_report"].pii_scan is not None
    assert updated["call_report"].status == "completed"


class TestGenerateReportPDF:
    """Test suite for generate_report_pdf function."""

    def create_sample_state(self, call_id="call-123", include_qa=True, include_pii=True):
        """Helper to create a sample state with compiled report."""
        qa_scores = None
        if include_qa:
            qa_scores = QAScoringResult(
                professionalism=4,
                empathy=5,
                problem_resolution=4,
                compliance=3,
                communication_clarity=4,
                overall_score=4.2,
                justification="Agent demonstrated good professionalism at 01:30 and strong empathy throughout the call."
            )

        pii_scan = None
        if include_pii:
            pii_scan = PIIScanResult(pii_detected=True, affected_fields=["email", "phone"])

        report = CallReport(
            call_id=call_id,
            timestamp="2024-01-15T10:30:00Z",
            audio_filename="call_123.wav",
            transcription=TranscriptionResult(
                segments=[TranscriptionSegment(start=0.0, end=10.0, text="Sample transcript", confidence=0.95)],
                call_id=call_id
            ),
            transcript_text="Sample transcript of the call",
            summary="This is a sample call summary with important details.",
            qa_scores=qa_scores,
            pii_scan=pii_scan,
            status="completed",
            error=None
        )

        return {"call_report": report}

    def test_generate_report_pdf_returns_bytes(self):
        """Test that generate_report_pdf returns bytes."""
        state = self.create_sample_state()
        result = generate_report_pdf(state)

        assert isinstance(result, bytes)
        assert len(result) > 0

    def test_generate_report_pdf_contains_pdf_signature(self):
        """Test that the generated bytes contain PDF signature."""
        state = self.create_sample_state()
        result = generate_report_pdf(state)

        assert result.startswith(b"%PDF")

    def test_generate_report_pdf_with_call_id(self):
        """Test that PDF generates successfully with custom call ID."""
        state = self.create_sample_state(call_id="call-xyz-789")
        result = generate_report_pdf(state)

        assert isinstance(result, bytes)
        assert result.startswith(b"%PDF")
        assert len(result) > 500

    def test_generate_report_pdf_with_qa_scores(self):
        """Test that PDF generates successfully with QA scores."""
        state = self.create_sample_state(include_qa=True)
        result = generate_report_pdf(state)

        assert isinstance(result, bytes)
        assert result.startswith(b"%PDF")
        assert len(result) > 1000

    def test_generate_report_pdf_without_qa_scores(self):
        """Test that PDF handles missing QA scores gracefully."""
        state = self.create_sample_state(include_qa=False)
        result = generate_report_pdf(state)

        assert isinstance(result, bytes)
        assert len(result) > 0

    def test_generate_report_pdf_with_pii_flags(self):
        """Test that PDF generates successfully with PII flags."""
        state = self.create_sample_state(include_pii=True)
        result = generate_report_pdf(state)

        assert isinstance(result, bytes)
        assert result.startswith(b"%PDF")
        assert len(result) > 1000

    def test_generate_report_pdf_without_pii_scan(self):
        """Test that PDF handles missing PII scan gracefully."""
        state = self.create_sample_state(include_pii=False)
        result = generate_report_pdf(state)

        assert isinstance(result, bytes)
        assert len(result) > 0

    def test_generate_report_pdf_no_call_report(self):
        """Test that PDF generation handles missing call_report."""
        state = {"call_report": None}
        result = generate_report_pdf(state)

        assert isinstance(result, bytes)
        assert len(result) > 0
        assert result.startswith(b"%PDF")

    def test_generate_report_pdf_with_long_summary(self):
        """Test that PDF truncates very long summaries."""
        long_summary = "A" * 300
        state = self.create_sample_state()
        state["call_report"].summary = long_summary

        result = generate_report_pdf(state)

        assert isinstance(result, bytes)
        assert len(result) > 0

    def test_generate_report_pdf_status_uppercase(self):
        """Test that PDF handles different status values."""
        state = self.create_sample_state()
        state["call_report"].status = "completed"
        result = generate_report_pdf(state)

        assert isinstance(result, bytes)
        assert result.startswith(b"%PDF")
        assert len(result) > 500

    def test_generate_report_pdf_with_failed_status(self):
        """Test PDF generation with failed status."""
        state = self.create_sample_state()
        state["call_report"].status = "failed"
        state["call_report"].error = "Processing error"

        result = generate_report_pdf(state)

        assert isinstance(result, bytes)
        assert len(result) > 0


class TestGenerateReportJSON:
    """Test suite for generate_report_json function."""

    def create_sample_state(self, call_id="call-123"):
        """Helper to create a sample state with compiled report."""
        qa_scores = QAScoringResult(
            professionalism=4,
            empathy=5,
            problem_resolution=4,
            compliance=3,
            communication_clarity=4,
            overall_score=4.2,
            justification="Agent demonstrated good professionalism and strong empathy."
        )

        pii_scan = PIIScanResult(pii_detected=True, affected_fields=["email"])

        report = CallReport(
            call_id=call_id,
            timestamp="2024-01-15T10:30:00Z",
            audio_filename="call_123.wav",
            transcription=TranscriptionResult(
                segments=[TranscriptionSegment(start=0.0, end=10.0, text="Sample", confidence=0.95)],
                call_id=call_id
            ),
            transcript_text="Sample transcript",
            summary="Sample summary",
            qa_scores=qa_scores,
            pii_scan=pii_scan,
            status="completed",
            error=None
        )

        return {"call_report": report}

    def test_generate_report_json_returns_string(self):
        """Test that generate_report_json returns a string."""
        state = self.create_sample_state()
        result = generate_report_json(state)

        assert isinstance(result, str)
        assert len(result) > 0

    def test_generate_report_json_is_valid_json(self):
        """Test that the returned string is valid JSON."""
        state = self.create_sample_state()
        result = generate_report_json(state)

        parsed = json.loads(result)
        assert isinstance(parsed, dict)

    def test_generate_report_json_contains_call_id(self):
        """Test that JSON contains the call ID."""
        state = self.create_sample_state(call_id="call-test-456")
        result = generate_report_json(state)

        parsed = json.loads(result)
        assert parsed["call_id"] == "call-test-456"

    def test_generate_report_json_contains_timestamp(self):
        """Test that JSON contains the timestamp."""
        state = self.create_sample_state()
        result = generate_report_json(state)

        parsed = json.loads(result)
        assert "timestamp" in parsed
        assert parsed["timestamp"] == "2024-01-15T10:30:00Z"

    def test_generate_report_json_contains_status(self):
        """Test that JSON contains the status."""
        state = self.create_sample_state()
        result = generate_report_json(state)

        parsed = json.loads(result)
        assert "status" in parsed
        assert parsed["status"] == "completed"

    def test_generate_report_json_contains_summary(self):
        """Test that JSON contains the summary."""
        state = self.create_sample_state()
        result = generate_report_json(state)

        parsed = json.loads(result)
        assert "summary" in parsed
        assert "Sample summary" in parsed["summary"]

    def test_generate_report_json_contains_qa_scores(self):
        """Test that JSON contains QA scores."""
        state = self.create_sample_state()
        result = generate_report_json(state)

        parsed = json.loads(result)
        assert "qa_scores" in parsed
        assert parsed["qa_scores"]["overall_score"] == 4.2

    def test_generate_report_json_contains_pii_scan(self):
        """Test that JSON contains PII scan results."""
        state = self.create_sample_state()
        result = generate_report_json(state)

        parsed = json.loads(result)
        assert "pii_scan" in parsed
        assert parsed["pii_scan"]["pii_detected"] is True

    def test_generate_report_json_no_call_report(self):
        """Test that JSON generation handles missing call_report."""
        state = {"call_report": None}
        result = generate_report_json(state)

        assert isinstance(result, str)
        parsed = json.loads(result)
        assert parsed == {}

    def test_generate_report_json_indentation(self):
        """Test that JSON is properly formatted with 2-space indentation."""
        state = self.create_sample_state()
        result = generate_report_json(state)

        assert "  " in result
        parsed = json.loads(result)
        assert isinstance(parsed, dict)

    def test_generate_report_json_with_error(self):
        """Test JSON generation with error in report."""
        state = self.create_sample_state()
        state["call_report"].status = "failed"
        state["call_report"].error = "Processing timeout"

        result = generate_report_json(state)

        parsed = json.loads(result)
        assert parsed["status"] == "failed"
        assert parsed["error"] == "Processing timeout"

    def test_generate_report_json_transcript_included(self):
        """Test that transcript text is included in JSON."""
        state = self.create_sample_state()
        state["call_report"].transcript_text = "This is the full transcript"

        result = generate_report_json(state)

        parsed = json.loads(result)
        assert "transcript_text" in parsed
        assert "full transcript" in parsed["transcript_text"]
