INJECTION_PATTERNS = [
    (r"(?i)ignore\s+(?:the\s+)?previous", "ignore_previous"),
    (r"(?i)ignore\s+(?:the\s+)?prior", "ignore_prior"),
    (r"(?i)disregard\s+(?:the\s+)?prior", "disregard_prior"),
    (r"(?i)forget\s+(?:the\s+)?previous", "forget_previous"),
    (r"(?i)(?:reveal|show|leak|display|print)\s+(?:the\s+)?prompt", "prompt_leak"),
    (r"(?i)(?:what|can you tell me)\s+(?:is\s+)?(?:the\s+)?prompt\??", "prompt_leak_question"),
    (r"(?i)system\s+prompt\s*:", "system_prompt_inject"),
    (r"<<SYS>>", "llama_system_tag"),
    (r"\[INST\]", "llama_inst_tag"),
    (r"\[/INST\]", "llama_inst_close_tag"),
    (r"(?i)(?:switch|change|assume|play|act as)\s+(?:the\s+)?(?:role|persona)", "role_switch"),
    (r"(?i)(?:new|different|additional|following)\s+instructions?", "new_instructions"),
    (r"(?i)(?:dan\s+mode|do\s+anything\s+now)", "dan_mode"),
    (r"(?i)jailbreak", "jailbreak"),
    (r"(?i)(?:override|bypass|disable)\s+(?:the\s+)?safety", "override_safety"),
    (r"(?i)ignore\s+(?:the\s+)?transcript", "ignore_transcript"),
    (r"(?i)(?:inject|add|insert)\s+(?:to\s+)?(?:the\s+)?conversation", "conversation_inject"),
    (r"(?i)(?:social\s+engineering|manipulate|trick|deceive)", "social_engineering"),
    (r"(?i)(?:translate|convert)\s+(?:to|in)\s+(?:another|different)\s+language", "translate_attack"),
    (r"(?i)ignore\s+(?:the\s+)?safety", "ignore_safety"),
    (r"(?i)(?:override|bypass)\s+(?:the\s+)?system", "system_override"),
    (r"(?i)(?:reveal|expose|show|leak|disclose)\s+(?:your\s+)?(?:system|inner|internal)", "reveal_attack"),
]
